# Generated by Django 3.0.1 on 2023-12-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articale',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articales', to='ss.Person'),
        ),
    ]
